

[node] #地址列表，注意是10进制
#终端地址目标选择方式： 
#    1. "random"  从下方 地址池 addrPollRangeRange 范围内随机选择N个终端进行下发测试,N的取值是 下方 randomSelectNum 范围内随机生成
#    2. "fixed"   从下方 "fixAddrList" 数组内指定测试终端进行下发测试
testAddrSelect =  "random"

addrPollRangeRange = [1,9]  #地址池范围 10进制
randomSelectNum = [8,9]       #随机选择测试终端个数 10进制
fixAddrList = [1,2,4,8,9,11,12,13,15,17,18,21,23,24,27,28,30,31,] #指定固件终端 10进制


[mac] #mac层参数
pingPeriod = 32 
beaconTimeInterval = 64000 #单位ms
# offsetSelect = "fixed" #偏移方式选择 random 或者 fixed
offsetSelect = "fixed" 

[test] #测试参数
loopCnt = 10000 #测试循环次数

[log]
path = "./log/run.log"
